### ISSUE TITLE
router "/aa/:name" can match "/aa.xml/aa.xml"

### ISSUE THREAD

**Issue by runner361** [beego/beego#4946]
https://github.com/beego/beego/blob/411fbb8cdb4424518e75ad3d6882635de0dcb397/server/web/tree.go#L344

This modification is still not sufficient，for router “/v1/yangeryl/:name”  url like "/v1/yangeryl.xml/yangeryl.xml" can also be matched
![image](https://user-images.githubusercontent.com/5164276/168745866-a94dcc4b-4626-4337-92a2-d33374f9d1bf.png)

**Comment by flycash** [comment]
This was fixed, you can upgrade the Beego version

**Comment by runner361** [comment]
Both v2.0.2 and v1.12.4  have this problem ,and I  know your fix about "[pick the fix 4459: /abc.html/aaa match /abc/aaa](https://github.com/beego/beego/commit/e593efdb1566e467e4620bac45fa189c117bb1b3)"
but the modification is still not sufficient, for router "/v1/aa/bb/:name" ,url "/v1/aa.xml/bb/aa.xml"  can also be matched. The key here is keep  the last ":name"(aa.xml) and the fix route(aa) with “.xml .json .html” suffix the same.

**Comment by flycash** [comment]
Sorry I am busy now, so can you help to fix this?

**Comment by runner361** [comment]
OK,issue was fixed
